/**
 * Describes the TreeView action types.
 *
 * @author Chamara Chathuranga
 */

export const SET_SELECTED_CATEGORY_LIST = "SET_SELECTED_CATEGORY_LIST";
export const REMOVE_SELECTED_CATEGORY_ITEM = "REMOVE_SELECTED_CATEGORY_ITEM";
export const CLEAR_SELECTED_CATEGORY_LIST = "CLEAR_SELECTED_CATEGORY_LIST";

export const TOGGLE_SELECTED_CATEGORY_VIEW_TYPE =
  "TOGGLE_SELECTED_CATEGORY_VIEW_TYPE";
